// Centralized visual asset registry for Mancora Kite Club.
// Replace images here to update UI, hero sliders, trips, sponsors, and campaign sets without touching components.

const imageRegistry = Object.freeze({
  "chatbot ia.mp4": new URL("../assets/chatbot ia.mp4", import.meta.url).href,
  "LOGOS KITE CLUB/LOGO-kite-new.webp": new URL("../assets/LOGOS KITE CLUB/LOGO-kite-new.webp", import.meta.url).href,
  "LOGOS KITE CLUB/kite-LOGO-COMPLETE.webp": new URL("../assets/LOGOS KITE CLUB/kite-LOGO-COMPLETE.webp", import.meta.url).href,
  "fotos trip/DSC04250.webp": new URL("../assets/fotos trip/DSC04250.webp", import.meta.url).href,
  "fotos trip/DSC01083.webp": new URL("../assets/fotos trip/DSC01083.webp", import.meta.url).href,
  "fotos mancora y mas/DSC03697.webp": new URL("../assets/fotos mancora y mas/DSC03697.webp", import.meta.url).href,
  "fotos mancora y mas/IMG_3893.webp": new URL("../assets/fotos mancora y mas/IMG_3893.webp", import.meta.url).href,
  "fotos trip/DSC03805.webp": new URL("../assets/fotos trip/DSC03805.webp", import.meta.url).href,
  "fotos clases/DSC02370.webp": new URL("../assets/fotos clases/DSC02370.webp", import.meta.url).href,
  "fotos trip/DSC03756.webp": new URL("../assets/fotos trip/DSC03756.webp", import.meta.url).href,
  "fotos trip/DSC03906.webp": new URL("../assets/fotos trip/DSC03906.webp", import.meta.url).href,
  "fotos trip/DSC00055.webp": new URL("../assets/fotos trip/DSC00055.webp", import.meta.url).href,
  "fotos trip/DSC00285.webp": new URL("../assets/fotos trip/DSC00285.webp", import.meta.url).href,
  "fotos trip/DSC03882.webp": new URL("../assets/fotos trip/DSC03882.webp", import.meta.url).href,
  "fotos trip/DSC03821.webp": new URL("../assets/fotos trip/DSC03821.webp", import.meta.url).href,
  "fotos trip/DSC03453.webp": new URL("../assets/fotos trip/DSC03453.webp", import.meta.url).href,
  "fotos trip/DSC03368.webp": new URL("../assets/fotos trip/DSC03368.webp", import.meta.url).href,
  "fotos trip/DSC02105.webp": new URL("../assets/fotos trip/DSC02105.webp", import.meta.url).href,
  "fotos trip/DSC02043.webp": new URL("../assets/fotos trip/DSC02043.webp", import.meta.url).href,
  "fotos trip/DSC01796.webp": new URL("../assets/fotos trip/DSC01796.webp", import.meta.url).href,
  "fotos trip/DSC01195.webp": new URL("../assets/fotos trip/DSC01195.webp", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt1.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt1.jpg", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt2.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt2.jpg", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt8.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt8.jpg", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt6.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt6.jpg", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt7.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt7.jpg", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt4.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt4.jpg", import.meta.url).href,
  "imagenes-kitsurfing-lessons/posicionk3.jpg": new URL("../assets/imagenes-kitsurfing-lessons/posicionk3.jpg", import.meta.url).href,
  "imagenes-kitsurfing-lessons/posicionk4.jpg": new URL("../assets/imagenes-kitsurfing-lessons/posicionk4.jpg", import.meta.url).href,
  "imagenes-kitsurfing-lessons/posicionk5.jpg": new URL("../assets/imagenes-kitsurfing-lessons/posicionk5.jpg", import.meta.url).href,
  "imagenes-kitsurfing-lessons/posicionk6.jpg": new URL("../assets/imagenes-kitsurfing-lessons/posicionk6.jpg", import.meta.url).href,
  "fotos clases/DSC07692.webp": new URL("../assets/fotos clases/DSC07692.webp", import.meta.url).href,
  "imagenes-wingfoil/posicionw1.jpg": new URL("../assets/imagenes-wingfoil/posicionw1.jpg", import.meta.url).href,
  "imagenes-wingfoil/posicionw8.jpg": new URL("../assets/imagenes-wingfoil/posicionw8.jpg", import.meta.url).href,
  "imagenes-wingfoil/posicionw2.jpg": new URL("../assets/imagenes-wingfoil/posicionw2.jpg", import.meta.url).href,
  "imagenes-home/posicion12.jpg": new URL("../assets/imagenes-home/posicion12.jpg", import.meta.url).href,
  "imagenes-home/posicion17.jpg": new URL("../assets/imagenes-home/posicion17.jpg", import.meta.url).href,
  "imagenes-home/posicion18.jpg": new URL("../assets/imagenes-home/posicion18.jpg", import.meta.url).href,
  "fotos mancora y mas/DSC05860.webp": new URL("../assets/fotos mancora y mas/DSC05860.webp", import.meta.url).href,
  "fotos mancora y mas/IMG_3603.webp": new URL("../assets/fotos mancora y mas/IMG_3603.webp", import.meta.url).href,
  "fotos trip/DSC03770.webp": new URL("../assets/fotos trip/DSC03770.webp", import.meta.url).href,
  "imagenes-hotel/main.jpg": new URL("../assets/imagenes-hotel/main.jpg", import.meta.url).href,
  "imagenes-hotel/DSC05231.jpg": new URL("../assets/imagenes-hotel/DSC05231.jpg", import.meta.url).href,
  "imagenes-hotel/DSC04826.jpg": new URL("../assets/imagenes-hotel/DSC04826.jpg", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC04823.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC04823.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05161.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05161.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05200.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05200.webp", import.meta.url).href,
  "fotos comunidad/DSC09030.webp": new URL("../assets/fotos comunidad/DSC09030.webp", import.meta.url).href,
  "fotos comunidad/DSC08865.webp": new URL("../assets/fotos comunidad/DSC08865.webp", import.meta.url).href,
  "fotos comunidad/DSC07625.webp": new URL("../assets/fotos comunidad/DSC07625.webp", import.meta.url).href,
  "imagenes-home/posicion6.jpg": new URL("../assets/imagenes-home/posicion6.jpg", import.meta.url).href,
  "imagenes-home/posicion5.jpg": new URL("../assets/imagenes-home/posicion5.jpg", import.meta.url).href,
  "imagenes-home/posicion4.jpg": new URL("../assets/imagenes-home/posicion4.jpg", import.meta.url).href,
  "imagenes-home/posicion3.jpg": new URL("../assets/imagenes-home/posicion3.jpg", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05231.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05231.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05127.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05127.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05120-HDR.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05120-HDR.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05085-HDR.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05085-HDR.webp", import.meta.url).href,
  "fotos clases/DSC04672.webp": new URL("../assets/fotos clases/DSC04672.webp", import.meta.url).href,
  "fotos clases/DSC05456.webp": new URL("../assets/fotos clases/DSC05456.webp", import.meta.url).href,
  "fotos clases/DSC05783.webp": new URL("../assets/fotos clases/DSC05783.webp", import.meta.url).href,
  "fotos clases/DSC05905.webp": new URL("../assets/fotos clases/DSC05905.webp", import.meta.url).href,
  "fotos clases/DSC05924.webp": new URL("../assets/fotos clases/DSC05924.webp", import.meta.url).href,
  "LOGOS KITE CLUB/95b03a84-2865-4eda-89ae-26b332f99bb5.webp": new URL("../assets/LOGOS KITE CLUB/95b03a84-2865-4eda-89ae-26b332f99bb5.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/main.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/main.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/cuartonazi.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/cuartonazi.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/habitacion.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/habitacion.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/image.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/image.webp", import.meta.url).href,
  "imagenes-wingfoil/posicionw4.jpg": new URL("../assets/imagenes-wingfoil/posicionw4.jpg", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt3.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt3.jpg", import.meta.url).href,
  "imagenes-wingfoil/posicionw5.jpg": new URL("../assets/imagenes-wingfoil/posicionw5.jpg", import.meta.url).href,
  "imagenes-wingfoil/posicionw7.jpg": new URL("../assets/imagenes-wingfoil/posicionw7.jpg", import.meta.url).href,
  "imagenes-home/posicion22.png": new URL("../assets/imagenes-home/posicion22.png", import.meta.url).href,
  "imagenes-home/posicion14y27.jpg": new URL("../assets/imagenes-home/posicion14y27.jpg", import.meta.url).href,
  "imagenes-kitsurfing-lessons/posicionk1.jpg": new URL("../assets/imagenes-kitsurfing-lessons/posicionk1.jpg", import.meta.url).href,
  "imagenes-kitsurfing-lessons/posicionk2.jpg": new URL("../assets/imagenes-kitsurfing-lessons/posicionk2.jpg", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt9.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt9.jpg", import.meta.url).href,
  "imagenes-home/posicion26.jpg": new URL("../assets/imagenes-home/posicion26.jpg", import.meta.url).href,
  "imagenes-home/posicion21.jpg": new URL("../assets/imagenes-home/posicion21.jpg", import.meta.url).href,
  "imagenes-home/posicion29.jpg": new URL("../assets/imagenes-home/posicion29.jpg", import.meta.url).href,
  "LOGOS KITE CLUB/Logo-duotone.webp": new URL("../assets/LOGOS KITE CLUB/Logo-duotone.webp", import.meta.url).href,
  "LOGOS KITE CLUB/Logo_ozone.webp": new URL("../assets/LOGOS KITE CLUB/Logo_ozone.webp", import.meta.url).href,
  "LOGOS KITE CLUB/Logo-Ride.webp": new URL("../assets/LOGOS KITE CLUB/Logo-Ride.webp", import.meta.url).href,
  "LOGOS KITE CLUB/Logo-slingshot.webp": new URL("../assets/LOGOS KITE CLUB/Logo-slingshot.webp", import.meta.url).href,
  "fotos equipo/DSC07657.webp": new URL("../assets/fotos equipo/DSC07657.webp", import.meta.url).href,
  "fotos home/DSC01032.webp": new URL("../assets/fotos home/DSC01032.webp", import.meta.url).href,
  "fotos home/DSC07629.webp": new URL("../assets/fotos home/DSC07629.webp", import.meta.url).href,
  "fotos home/DSC08775.webp": new URL("../assets/fotos home/DSC08775.webp", import.meta.url).href,
  "fotos home/DSC07230.webp": new URL("../assets/fotos home/DSC07230.webp", import.meta.url).href,
  "fotos home/DSC09510.webp": new URL("../assets/fotos home/DSC09510.webp", import.meta.url).href,
  "fotos home/DSC05908.webp": new URL("../assets/fotos home/DSC05908.webp", import.meta.url).href,
  "fotos home/DSC00231.webp": new URL("../assets/fotos home/DSC00231.webp", import.meta.url).href,
  "fotos home/DSC00406.webp": new URL("../assets/fotos home/DSC00406.webp", import.meta.url).href,
  "fotos home/DSC04249 2.webp": new URL("../assets/fotos home/DSC04249 2.webp", import.meta.url).href,
  "fotos home/IMG_5230.webp": new URL("../assets/fotos home/IMG_5230.webp", import.meta.url).href,
  "fotos comunidad/IMG_2917.webp": new URL("../assets/fotos comunidad/IMG_2917.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC09732.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC09732.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05185.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05185.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05137-HDR.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05137-HDR.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05113-HDR.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05113-HDR.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05056.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05056.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC04995.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC04995.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC04848.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC04848.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC04859.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC04859.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC09916.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC09916.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC09741.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC09741.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05144.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05144.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05041.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05041.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05145.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05145.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05030.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05030.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05159.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05159.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05173.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05173.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05016-Pano-HDR.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05016-Pano-HDR.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC09659.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC09659.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC09821.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC09821.webp", import.meta.url).href,
  "fotos wingfoil/DSC00360.webp": new URL("../assets/fotos wingfoil/DSC00360.webp", import.meta.url).href,
  "fotos clases/DSC00104.webp": new URL("../assets/fotos clases/DSC00104.webp", import.meta.url).href,
  "fotos clases/DSC00146.webp": new URL("../assets/fotos clases/DSC00146.webp", import.meta.url).href,
  "fotos clases/DSC01023.webp": new URL("../assets/fotos clases/DSC01023.webp", import.meta.url).href,
  "fotos clases/DSC01245.webp": new URL("../assets/fotos clases/DSC01245.webp", import.meta.url).href,
  "fotos clases/DSC01373.webp": new URL("../assets/fotos clases/DSC01373.webp", import.meta.url).href,
  "fotos comunidad/DSC02939.webp": new URL("../assets/fotos comunidad/DSC02939.webp", import.meta.url).href,
  "fotos comunidad/DSC04277.webp": new URL("../assets/fotos comunidad/DSC04277.webp", import.meta.url).href,
  "fotos comunidad/IMG_4993.webp": new URL("../assets/fotos comunidad/IMG_4993.webp", import.meta.url).href,
  "fotos comunidad/DSC06099.webp": new URL("../assets/fotos comunidad/DSC06099.webp", import.meta.url).href,
  "fotos comunidad/DSC09008.webp": new URL("../assets/fotos comunidad/DSC09008.webp", import.meta.url).href,
  "fotos mancora y mas/DSC02032.webp": new URL("../assets/fotos mancora y mas/DSC02032.webp", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt5.png": new URL("../assets/imagenes-kitesurfing/posicionkt5.png", import.meta.url).href,
  "imagenes-kitesurfing/posicionkt10.jpg": new URL("../assets/imagenes-kitesurfing/posicionkt10.jpg", import.meta.url).href,
  "imagenes-home/posicion1.jpg": new URL("../assets/imagenes-home/posicion1.jpg", import.meta.url).href,
  "imagenes-home/posicion28.jpg": new URL("../assets/imagenes-home/posicion28.jpg", import.meta.url).href,
  "fotos trip/DSC07363.webp": new URL("../assets/fotos trip/DSC07363.webp", import.meta.url).href,
  "fotos trip/DSC07365.webp": new URL("../assets/fotos trip/DSC07365.webp", import.meta.url).href,
  "fotos trip/DSC07356.webp": new URL("../assets/fotos trip/DSC07356.webp", import.meta.url).href,
  "fotos trip/DSC07329.webp": new URL("../assets/fotos trip/DSC07329.webp", import.meta.url).href,
  "fotos trip/DSC07322.webp": new URL("../assets/fotos trip/DSC07322.webp", import.meta.url).href,
  "fotos trip/DSC07145.webp": new URL("../assets/fotos trip/DSC07145.webp", import.meta.url).href,
  "fotos trip/DSC06167.webp": new URL("../assets/fotos trip/DSC06167.webp", import.meta.url).href,
  "fotos trip/DSC08247.webp": new URL("../assets/fotos trip/DSC08247.webp", import.meta.url).href,
  "fotos trip/DSC05804.webp": new URL("../assets/fotos trip/DSC05804.webp", import.meta.url).href,
  "fotos trip/DSC05388.webp": new URL("../assets/fotos trip/DSC05388.webp", import.meta.url).href,
  "fotos trip/DSC05358.webp": new URL("../assets/fotos trip/DSC05358.webp", import.meta.url).href,
  "fotos trip/DSC05014.webp": new URL("../assets/fotos trip/DSC05014.webp", import.meta.url).href,
  "fotos trip/DSC04699.webp": new URL("../assets/fotos trip/DSC04699.webp", import.meta.url).href,
  "fotos trip/DSC04697.webp": new URL("../assets/fotos trip/DSC04697.webp", import.meta.url).href,
  "fotos trip/DSC04185.webp": new URL("../assets/fotos trip/DSC04185.webp", import.meta.url).href,
  "fotos trip/DSC04260.webp": new URL("../assets/fotos trip/DSC04260.webp", import.meta.url).href,
  "fotos trip/DSC09130.webp": new URL("../assets/fotos trip/DSC09130.webp", import.meta.url).href,
  "fotos trip/DSC00587.webp": new URL("../assets/fotos trip/DSC00587.webp", import.meta.url).href,
  "fotos paquetes surf y hotel/IMG_6558.webp": new URL("../assets/fotos paquetes surf y hotel/IMG_6558.webp", import.meta.url).href,
  "fotos paquetes surf y hotel/DSC01088.webp": new URL("../assets/fotos paquetes surf y hotel/DSC01088.webp", import.meta.url).href,
  "fotos paquetes surf y hotel/DSC01003.webp": new URL("../assets/fotos paquetes surf y hotel/DSC01003.webp", import.meta.url).href,
  "fotos paquetes surf y hotel/DSC04263.webp": new URL("../assets/fotos paquetes surf y hotel/DSC04263.webp", import.meta.url).href,
  "fotos clases/DSC00433.webp": new URL("../assets/fotos clases/DSC00433.webp", import.meta.url).href,
  "fotos clases/6dcb0367aacb508f64060f4c9f1b55f6.webp": new URL("../assets/fotos clases/6dcb0367aacb508f64060f4c9f1b55f6.webp", import.meta.url).href,
  "fotos clases/6e7948ecd00eab6741c0568662f61a53.webp": new URL("../assets/fotos clases/6e7948ecd00eab6741c0568662f61a53.webp", import.meta.url).href,
  "fotos clases/A66CFBBB-9C61-4CA4-9125-1360D41E5309.webp": new URL("../assets/fotos clases/A66CFBBB-9C61-4CA4-9125-1360D41E5309.webp", import.meta.url).href,
  "fotos clases/DSC02331.webp": new URL("../assets/fotos clases/DSC02331.webp", import.meta.url).href,
  "fotos clases/DSC01412.webp": new URL("../assets/fotos clases/DSC01412.webp", import.meta.url).href,
  "fotos clases/DSC01394.webp": new URL("../assets/fotos clases/DSC01394.webp", import.meta.url).href,
  "fotos clases/DSC04663.webp": new URL("../assets/fotos clases/DSC04663.webp", import.meta.url).href,
  "fotos clases/DSC04664.webp": new URL("../assets/fotos clases/DSC04664.webp", import.meta.url).href,
  "fotos clases/DSC04670.webp": new URL("../assets/fotos clases/DSC04670.webp", import.meta.url).href,
  "fotos clases/DSC04595.webp": new URL("../assets/fotos clases/DSC04595.webp", import.meta.url).href,
  "fotos clases/DSC04273.webp": new URL("../assets/fotos clases/DSC04273.webp", import.meta.url).href,
  "fotos clases/DSC04671.webp": new URL("../assets/fotos clases/DSC04671.webp", import.meta.url).href,
  "fotos clases/DSC04677.webp": new URL("../assets/fotos clases/DSC04677.webp", import.meta.url).href,
  "fotos clases/DSC04682.webp": new URL("../assets/fotos clases/DSC04682.webp", import.meta.url).href,
  "fotos clases/DSC04679.webp": new URL("../assets/fotos clases/DSC04679.webp", import.meta.url).href,
  "fotos clases/DSC04766.webp": new URL("../assets/fotos clases/DSC04766.webp", import.meta.url).href,
  "fotos clases/DSC05197.webp": new URL("../assets/fotos clases/DSC05197.webp", import.meta.url).href,
  "fotos clases/DSC05907.webp": new URL("../assets/fotos clases/DSC05907.webp", import.meta.url).href,
  "fotos clases/DSC05719.webp": new URL("../assets/fotos clases/DSC05719.webp", import.meta.url).href,
  "fotos clases/DSC05740.webp": new URL("../assets/fotos clases/DSC05740.webp", import.meta.url).href,
  "fotos clases/DSC05887.webp": new URL("../assets/fotos clases/DSC05887.webp", import.meta.url).href,
  "fotos clases/DSC06975 2.webp": new URL("../assets/fotos clases/DSC06975 2.webp", import.meta.url).href,
  "fotos clases/DSC06979 2.webp": new URL("../assets/fotos clases/DSC06979 2.webp", import.meta.url).href,
  "fotos clases/DSC07665.webp": new URL("../assets/fotos clases/DSC07665.webp", import.meta.url).href,
  "fotos clases/DSC07683.webp": new URL("../assets/fotos clases/DSC07683.webp", import.meta.url).href,
  "fotos clases/DSC07693.webp": new URL("../assets/fotos clases/DSC07693.webp", import.meta.url).href,
  "fotos clases/DSC07694.webp": new URL("../assets/fotos clases/DSC07694.webp", import.meta.url).href,
  "fotos clases/DSC06284.webp": new URL("../assets/fotos clases/DSC06284.webp", import.meta.url).href,
  "fotos clases/DSC06276.webp": new URL("../assets/fotos clases/DSC06276.webp", import.meta.url).href,
  "fotos clases/DSC00144.webp": new URL("../assets/fotos clases/DSC00144.webp", import.meta.url).href,
  "fotos clases/DSC00102.webp": new URL("../assets/fotos clases/DSC00102.webp", import.meta.url).href,
  "fotos clases/DSC00018.webp": new URL("../assets/fotos clases/DSC00018.webp", import.meta.url).href,
  "fotos clases/DSC07673.webp": new URL("../assets/fotos clases/DSC07673.webp", import.meta.url).href,
  "fotos clases/DSC09584.webp": new URL("../assets/fotos clases/DSC09584.webp", import.meta.url).href,
  "fotos clases/DSC09589.webp": new URL("../assets/fotos clases/DSC09589.webp", import.meta.url).href,
  "fotos clases/DSC09599.webp": new URL("../assets/fotos clases/DSC09599.webp", import.meta.url).href,
  "fotos clases/DSC09627.webp": new URL("../assets/fotos clases/DSC09627.webp", import.meta.url).href,
  "fotos clases/DSC09570.webp": new URL("../assets/fotos clases/DSC09570.webp", import.meta.url).href,
  "fotos wingfoil/DSC09982.webp": new URL("../assets/fotos wingfoil/DSC09982.webp", import.meta.url).href,
  "fotos wingfoil/DSC09936.webp": new URL("../assets/fotos wingfoil/DSC09936.webp", import.meta.url).href,
  "fotos wingfoil/DSC07146.webp": new URL("../assets/fotos wingfoil/DSC07146.webp", import.meta.url).href,
  "fotos wingfoil/DSC07130.webp": new URL("../assets/fotos wingfoil/DSC07130.webp", import.meta.url).href,
  "fotos wingfoil/DSC05634.webp": new URL("../assets/fotos wingfoil/DSC05634.webp", import.meta.url).href,
  "fotos wingfoil/DSC05417.webp": new URL("../assets/fotos wingfoil/DSC05417.webp", import.meta.url).href,
  "fotos wingfoil/DSC05369.webp": new URL("../assets/fotos wingfoil/DSC05369.webp", import.meta.url).href,
  "fotos wingfoil/DSC05362.webp": new URL("../assets/fotos wingfoil/DSC05362.webp", import.meta.url).href,
  "fotos wingfoil/DSC03425.webp": new URL("../assets/fotos wingfoil/DSC03425.webp", import.meta.url).href,
  "fotos wingfoil/DSC03295.webp": new URL("../assets/fotos wingfoil/DSC03295.webp", import.meta.url).href,
  "fotos wingfoil/DSC00036.webp": new URL("../assets/fotos wingfoil/DSC00036.webp", import.meta.url).href,
  "fotos wingfoil/DSC00021.webp": new URL("../assets/fotos wingfoil/DSC00021.webp", import.meta.url).href,
  "fotos wingfoil/DSC00008.webp": new URL("../assets/fotos wingfoil/DSC00008.webp", import.meta.url).href,
  "fotos mancora y mas/DSC02131.webp": new URL("../assets/fotos mancora y mas/DSC02131.webp", import.meta.url).href,
  "fotos mancora y mas/549ad1d90e9c3d743b9cc1055711b327.webp": new URL("../assets/fotos mancora y mas/549ad1d90e9c3d743b9cc1055711b327.webp", import.meta.url).href,
  "fotos mancora y mas/DSC00946.webp": new URL("../assets/fotos mancora y mas/DSC00946.webp", import.meta.url).href,
  "fotos mancora y mas/DSC00947.webp": new URL("../assets/fotos mancora y mas/DSC00947.webp", import.meta.url).href,
  "fotos mancora y mas/DSC00990.webp": new URL("../assets/fotos mancora y mas/DSC00990.webp", import.meta.url).href,
  "fotos mancora y mas/DSC01600.webp": new URL("../assets/fotos mancora y mas/DSC01600.webp", import.meta.url).href,
  "fotos mancora y mas/DSC01601.webp": new URL("../assets/fotos mancora y mas/DSC01601.webp", import.meta.url).href,
  "fotos mancora y mas/DSC02113.webp": new URL("../assets/fotos mancora y mas/DSC02113.webp", import.meta.url).href,
  "fotos mancora y mas/DSC02126.webp": new URL("../assets/fotos mancora y mas/DSC02126.webp", import.meta.url).href,
  "fotos mancora y mas/DSC02158.webp": new URL("../assets/fotos mancora y mas/DSC02158.webp", import.meta.url).href,
  "fotos mancora y mas/DSC02187.webp": new URL("../assets/fotos mancora y mas/DSC02187.webp", import.meta.url).href,
  "fotos mancora y mas/DSC02141.webp": new URL("../assets/fotos mancora y mas/DSC02141.webp", import.meta.url).href,
  "fotos mancora y mas/DSC02156.webp": new URL("../assets/fotos mancora y mas/DSC02156.webp", import.meta.url).href,
  "fotos mancora y mas/DSC03684.webp": new URL("../assets/fotos mancora y mas/DSC03684.webp", import.meta.url).href,
  "fotos mancora y mas/DSC03686.webp": new URL("../assets/fotos mancora y mas/DSC03686.webp", import.meta.url).href,
  "fotos mancora y mas/DSC05866.webp": new URL("../assets/fotos mancora y mas/DSC05866.webp", import.meta.url).href,
  "fotos mancora y mas/DSC05276.webp": new URL("../assets/fotos mancora y mas/DSC05276.webp", import.meta.url).href,
  "fotos mancora y mas/DSC05505 2.webp": new URL("../assets/fotos mancora y mas/DSC05505 2.webp", import.meta.url).href,
  "fotos mancora y mas/DSC05505.webp": new URL("../assets/fotos mancora y mas/DSC05505.webp", import.meta.url).href,
  "fotos mancora y mas/DSC09770.webp": new URL("../assets/fotos mancora y mas/DSC09770.webp", import.meta.url).href,
  "fotos mancora y mas/DSC09776.webp": new URL("../assets/fotos mancora y mas/DSC09776.webp", import.meta.url).href,
  "fotos mancora y mas/DSC09910.webp": new URL("../assets/fotos mancora y mas/DSC09910.webp", import.meta.url).href,
  "fotos mancora y mas/DSC09912.webp": new URL("../assets/fotos mancora y mas/DSC09912.webp", import.meta.url).href,
  "fotos mancora y mas/DSC09933.webp": new URL("../assets/fotos mancora y mas/DSC09933.webp", import.meta.url).href,
  "fotos mancora y mas/DSC09961.webp": new URL("../assets/fotos mancora y mas/DSC09961.webp", import.meta.url).href,
  "fotos mancora y mas/DSC08477.webp": new URL("../assets/fotos mancora y mas/DSC08477.webp", import.meta.url).href,
  "fotos mancora y mas/DSC08663.webp": new URL("../assets/fotos mancora y mas/DSC08663.webp", import.meta.url).href,
  "fotos mancora y mas/DSC07164.webp": new URL("../assets/fotos mancora y mas/DSC07164.webp", import.meta.url).href,
  "fotos mancora y mas/DSC03698.webp": new URL("../assets/fotos mancora y mas/DSC03698.webp", import.meta.url).href,
  "fotos mancora y mas/IMG_7170.webp": new URL("../assets/fotos mancora y mas/IMG_7170.webp", import.meta.url).href,
  "fotos mancora y mas/IMG_5443.webp": new URL("../assets/fotos mancora y mas/IMG_5443.webp", import.meta.url).href,
  "fotos comunidad/beach.webp": new URL("../assets/fotos comunidad/beach.webp", import.meta.url).href,
  "fotos comunidad/DSC09564.webp": new URL("../assets/fotos comunidad/DSC09564.webp", import.meta.url).href,
  "fotos comunidad/DSC09125.webp": new URL("../assets/fotos comunidad/DSC09125.webp", import.meta.url).href,
  "fotos comunidad/DSC09091.webp": new URL("../assets/fotos comunidad/DSC09091.webp", import.meta.url).href,
  "fotos comunidad/DSC08846.webp": new URL("../assets/fotos comunidad/DSC08846.webp", import.meta.url).href,
  "fotos comunidad/DSC09085.webp": new URL("../assets/fotos comunidad/DSC09085.webp", import.meta.url).href,
  "fotos comunidad/DSC08341.webp": new URL("../assets/fotos comunidad/DSC08341.webp", import.meta.url).href,
  "fotos comunidad/DSC07841.webp": new URL("../assets/fotos comunidad/DSC07841.webp", import.meta.url).href,
  "fotos comunidad/DSC07739.webp": new URL("../assets/fotos comunidad/DSC07739.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC04807.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC04807.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC04841.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC04841.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC04842.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC04842.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC05230.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC05230.webp", import.meta.url).href,
  "HOSPEDAJE KITE HOUSE/DSC09920.webp": new URL("../assets/HOSPEDAJE KITE HOUSE/DSC09920.webp", import.meta.url).href,
})

export function resolveImage(assetPath) {
  const resolved = imageRegistry[assetPath]

  if (!resolved) {
    throw new Error(`Image asset not registered: ${assetPath}`)
  }

  return resolved
}

const image = resolveImage

export const brandImages = Object.freeze({
  logoComplete: image("LOGOS KITE CLUB/kite-LOGO-COMPLETE.webp"),
  logoMark: image("LOGOS KITE CLUB/LOGO-kite-new.webp"),
  contactMark: image("LOGOS KITE CLUB/95b03a84-2865-4eda-89ae-26b332f99bb5.webp"),
  floatingWhatsAppMark: image("LOGOS KITE CLUB/LOGO-kite-new.webp"),
  sponsors: Object.freeze({
    duotone: image("LOGOS KITE CLUB/Logo-duotone.webp"),
    ozone: image("LOGOS KITE CLUB/Logo_ozone.webp"),
    ride: image("LOGOS KITE CLUB/Logo-Ride.webp"),
    slingshot: image("LOGOS KITE CLUB/Logo-slingshot.webp"),
  }),
})

export const mediaAssets = Object.freeze({
  chatbotVideo: image("chatbot ia.mp4"),
})

export const heroImages = Object.freeze({
  kite: Object.freeze({
    desktop: Object.freeze([image("imagenes-kitesurfing/posicionkt1.jpg"), image("fotos trip/DSC05804.webp"), image("fotos trip/DSC05388.webp")]),
    mobile: Object.freeze([image("imagenes-home/posicion5.jpg"), image("imagenes-home/posicion6.jpg"), image("imagenes-home/posicion4.jpg")]),
  }),
  lessons: Object.freeze({
    desktop: Object.freeze([image("imagenes-kitsurfing-lessons/posicionk3.jpg"), image("fotos clases/DSC02331.webp"), image("imagenes-kitsurfing-lessons/posicionk5.jpg")]),
    mobile: Object.freeze([image("imagenes-kitsurfing-lessons/posicionk6.jpg"), image("fotos clases/DSC09570.webp"), image("fotos clases/DSC07673.webp")]),
  }),
  wing: Object.freeze({
    desktop: Object.freeze([image("fotos wingfoil/DSC09936.webp"), image("fotos wingfoil/DSC07146.webp"), image("imagenes-wingfoil/posicionw8.jpg")]),
    mobile: Object.freeze([image("fotos wingfoil/DSC00036.webp"), image("imagenes-wingfoil/posicionw7.jpg"), image("imagenes-home/posicion26.jpg")]),
  }),
  surf: Object.freeze({
    desktop: Object.freeze([image("fotos mancora y mas/DSC00946.webp"), image("fotos mancora y mas/DSC00947.webp"), image("fotos mancora y mas/DSC01600.webp")]),
    mobile: Object.freeze([image("fotos mancora y mas/DSC03684.webp"), image("fotos mancora y mas/DSC03686.webp"), image("fotos mancora y mas/DSC03697.webp")]),
  }),
  stay: Object.freeze({
    desktop: Object.freeze([image("imagenes-hotel/main.jpg"), image("imagenes-hotel/DSC05231.jpg"), image("imagenes-hotel/DSC04826.jpg")]),
    mobile: Object.freeze([image("HOSPEDAJE KITE HOUSE/DSC04823.webp"), image("HOSPEDAJE KITE HOUSE/DSC05161.webp"), image("HOSPEDAJE KITE HOUSE/DSC05200.webp")]),
  }),
  community: Object.freeze({
    desktop: Object.freeze([image("fotos comunidad/IMG_2917.webp"), image("fotos comunidad/DSC09564.webp"), image("fotos comunidad/DSC09091.webp")]),
    mobile: Object.freeze([image("fotos comunidad/DSC09030.webp"), image("fotos comunidad/DSC08865.webp"), image("fotos comunidad/DSC07625.webp")]),
  }),
  blog: Object.freeze({
    desktop: Object.freeze([image("fotos mancora y mas/DSC02131.webp"), image("fotos mancora y mas/DSC02126.webp"), image("fotos mancora y mas/DSC02113.webp")]),
    mobile: Object.freeze([image("fotos mancora y mas/DSC02141.webp"), image("fotos mancora y mas/DSC02156.webp"), image("fotos mancora y mas/DSC02113.webp")]),
  }),
})

export const homeImages = Object.freeze({
  hero: Object.freeze({
    actionDesktop: image("fotos home/DSC01032.webp"),
    actionMobile: image("fotos home/DSC07629.webp"),
    waveDesktop: image("fotos home/DSC08775.webp"),
    waveMobile: image("fotos home/DSC07230.webp"),
    lifestyle: image("fotos home/DSC09510.webp"),
    beach: image("fotos home/DSC05908.webp"),
  }),
  storyFounder: image("fotos equipo/DSC07657.webp"),
})

export const tripsImages = Object.freeze({
  firstFly: Object.freeze({ hero: image("fotos trip/DSC04260.webp"), image1: image("fotos wingfoil/DSC00021.webp"), image2: image("HOSPEDAJE KITE HOUSE/DSC04842.webp") }),
  olasViento: Object.freeze({ hero: image("fotos paquetes surf y hotel/DSC01088.webp"), image1: image("fotos clases/DSC01394.webp"), image2: image("HOSPEDAJE KITE HOUSE/DSC04807.webp") }),
  soloSurf: Object.freeze({ hero: image("fotos mancora y mas/DSC00990.webp"), image1: image("fotos mancora y mas/DSC02158.webp"), image2: image("fotos clases/DSC00018.webp") }),
  rideTheCoast: Object.freeze({ hero: image("fotos trip/DSC07363.webp"), image1: image("fotos trip/DSC09130.webp"), image2: image("fotos wingfoil/DSC05362.webp") }),
})

export const sponsorImageSets = Object.freeze({
  default: Object.freeze(Object.values(brandImages.sponsors)),
  kiteSponsors: Object.freeze(Object.values(brandImages.sponsors)),
  futureSponsorA: Object.freeze([]),
  futureSponsorB: Object.freeze([]),
})

export function getSponsorImages(setName = 'default') {
  return sponsorImageSets[setName] || sponsorImageSets.default
}

export const remoteImages = Object.freeze({
  homeInstruction: image("fotos clases/DSC02331.webp"),
  homeStay: Object.freeze({
    main: image("HOSPEDAJE KITE HOUSE/DSC04807.webp"),
    pool: image("HOSPEDAJE KITE HOUSE/DSC04841.webp"),
    bedroom: image("HOSPEDAJE KITE HOUSE/habitacion.webp"),
  }),
  homeTestimonials: Object.freeze({
    tina: image("fotos comunidad/DSC09125.webp"),
    sarah: image("fotos comunidad/DSC08846.webp"),
    marc: image("fotos comunidad/DSC09008.webp"),
  }),
})

export const seoImages = Object.freeze({
  defaultOpenGraph: 'https://www.mancorakiteclub.com/assets/main-CpaNiQFq.webp',
})

export const componentImages = Object.freeze({
  "components/ActionHub.jsx": Object.freeze({
    chatbotVideo: image("chatbot ia.mp4"),
    logoKite: image("LOGOS KITE CLUB/LOGO-kite-new.webp"),
  }),
  "components/ChatbotMessage.jsx": Object.freeze({
    chatbotVideo: image("chatbot ia.mp4"),
  }),
  "components/FloatingWhatsApp.jsx": Object.freeze({
    clubLogo: image("LOGOS KITE CLUB/LOGO-kite-new.webp"),
  }),
  "content/trips.js": Object.freeze({
    firstFlyHero: image("fotos trip/DSC03805.webp"),
    firstFlyImg1: image("fotos wingfoil/DSC03425.webp"),
    firstFlyImg2: image("HOSPEDAJE KITE HOUSE/DSC04859.webp"),
    olasHero: image("fotos paquetes surf y hotel/DSC01003.webp"),
    olasImg1: image("fotos clases/DSC01373.webp"),
    olasImg2: image("HOSPEDAJE KITE HOUSE/DSC05173.webp"),
    soloSurfHero: image("fotos mancora y mas/DSC01601.webp"),
    soloSurfImg1: image("fotos mancora y mas/IMG_7170.webp"),
    soloSurfImg2: image("fotos clases/DSC00018.webp"),
    rideHero: image("fotos trip/DSC07356.webp"),
    rideImg1: image("fotos trip/DSC07329.webp"),
    rideImg2: image("fotos wingfoil/DSC00360.webp"),
  }),
  "lib/fullscreenHeroSlides.js": Object.freeze({
    kiteWideA: image("fotos trip/DSC03756.webp"),
    kiteWideB: image("fotos trip/DSC06167.webp"),
    kiteWideC: image("fotos trip/DSC03882.webp"),
    kitePortraitA: image("imagenes-kitesurfing/posicionkt5.png"),
    kitePortraitB: image("imagenes-kitesurfing/posicionkt9.jpg"),
    kitePortraitC: image("imagenes-kitesurfing/posicionkt10.jpg"),
    lessonWideA: image("fotos clases/DSC04663.webp"),
    lessonWideB: image("fotos clases/DSC04595.webp"),
    lessonWideC: image("imagenes-kitsurfing-lessons/posicionk5.jpg"),
    lessonPortraitA: image("imagenes-kitsurfing-lessons/posicionk6.jpg"),
    lessonPortraitB: image("fotos clases/DSC04273.webp"),
    lessonPortraitC: image("fotos clases/DSC09599.webp"),
    wingWideA: image("fotos wingfoil/DSC03295.webp"),
    wingWideB: image("fotos wingfoil/DSC00036.webp"),
    wingWideC: image("fotos wingfoil/DSC00008.webp"),
    wingPortraitA: image("imagenes-home/posicion28.jpg"),
    surfWideA: image("fotos mancora y mas/DSC00946.webp"),
    surfWideB: image("fotos mancora y mas/DSC00947.webp"),
    surfWideC: image("fotos mancora y mas/DSC01600.webp"),
    lifestylePortraitA: image("fotos comunidad/DSC08341.webp"),
    lifestylePortraitB: image("fotos comunidad/DSC09091.webp"),
    lifestylePortraitC: image("fotos comunidad/DSC09125.webp"),
    surfPortraitA: image("fotos mancora y mas/DSC03698.webp"),
    surfPortraitB: image("fotos mancora y mas/DSC09961.webp"),
    surfPortraitC: image("fotos mancora y mas/DSC02187.webp"),
    stayWideA: image("imagenes-hotel/main.jpg"),
    stayWideB: image("imagenes-hotel/DSC05231.jpg"),
    stayWideC: image("imagenes-hotel/DSC04826.jpg"),
    stayPortraitA: image("HOSPEDAJE KITE HOUSE/DSC04823.webp"),
    stayPortraitB: image("HOSPEDAJE KITE HOUSE/DSC05161.webp"),
    stayPortraitC: image("HOSPEDAJE KITE HOUSE/DSC05200.webp"),
    communityPortraitA: image("fotos comunidad/DSC09030.webp"),
    communityPortraitB: image("fotos comunidad/DSC08865.webp"),
    communityPortraitC: image("fotos comunidad/DSC07625.webp"),
  }),
  "pages/BuildPage.jsx": Object.freeze({
    actividadKitesurf: image("imagenes-home/posicion29.jpg"),
    actividadWingfoil: image("fotos wingfoil/DSC00008.webp"),
    actividadSurf: image("imagenes-kitesurfing/posicionkt8.jpg"),
    actividadSup: image("imagenes-home/posicion3.jpg"),
    nightcaption: image("HOSPEDAJE KITE HOUSE/DSC05230.webp"),
    DSC05231: image("HOSPEDAJE KITE HOUSE/DSC05231.webp"),
    buildHeroBg: {
      desktop: image("fotos trip/DSC08247.webp"),
      mobile: image("fotos mancora y mas/DSC02032.webp"),
    },
    DSC05120HDR: image("HOSPEDAJE KITE HOUSE/DSC05120-HDR.webp"),
    DSC05085HDR: image("HOSPEDAJE KITE HOUSE/DSC05085-HDR.webp"),
    hora0: image("fotos clases/DSC04672.webp"),
    hora3: image("fotos clases/DSC05456.webp"),
    hora6: image("fotos clases/DSC05783.webp"),
    hora10: image("fotos clases/DSC05905.webp"),
    hora15: image("fotos clases/DSC05924.webp"),
    kiteCarousel: [
      image("fotos trip/DSC05358.webp"),
      image("fotos trip/DSC05014.webp"),
      image("imagenes-home/posicion4.jpg"),
      image("imagenes-kitesurfing/posicionkt9.jpg"),
    ],
    wingCarousel: [
      image("fotos wingfoil/DSC00360.webp"),
    ],
    surfCarousel: [
      image("fotos mancora y mas/DSC01601.webp"),
      image("fotos mancora y mas/IMG_7170.webp"),
    ],
    supCarousel: [
      image("imagenes-home/posicion3.jpg"),
    ],
  }),
  "pages/ContactPage.jsx": Object.freeze({
    logoImg: image("LOGOS KITE CLUB/95b03a84-2865-4eda-89ae-26b332f99bb5.webp"),
    formDecorImg: image("fotos comunidad/DSC09085.webp"),
  }),
  "pages/StayPage.jsx": Object.freeze({
    heroImg: image("HOSPEDAJE KITE HOUSE/main.webp"),
    img1: image("HOSPEDAJE KITE HOUSE/cuartonazi.webp"),
    img2: image("HOSPEDAJE KITE HOUSE/habitacion.webp"),
    img3: image("HOSPEDAJE KITE HOUSE/DSC09920.webp"),
    img4: image("HOSPEDAJE KITE HOUSE/DSC09916.webp"),
    img5: image("HOSPEDAJE KITE HOUSE/image.webp"),
    // New categorized sets
    horizontal: [
      image("HOSPEDAJE KITE HOUSE/DSC09732.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05185.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05137-HDR.webp"),
      image("HOSPEDAJE KITE HOUSE/main.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05113-HDR.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05056.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC04995.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC04848.webp"),
    ],
    vertical: [
      image("HOSPEDAJE KITE HOUSE/DSC04841.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC09741.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05144.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05041.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05145.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05030.webp"),
    ],
    galleryFull: [
      image("HOSPEDAJE KITE HOUSE/DSC04859.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05185.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05137-HDR.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05113-HDR.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05056.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC04995.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC04848.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05127.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05159.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05173.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC05016-Pano-HDR.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC09659.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC09821.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC04842.webp"),
      image("HOSPEDAJE KITE HOUSE/DSC09741.webp"),
    ],
  }),
  "pages/TripsPage.jsx": Object.freeze({
    heroImg: image("fotos trip/DSC07356.webp"),
    firstFlyImg: image("fotos trip/DSC04185.webp"),
    olasVientoImg: image("fotos paquetes surf y hotel/DSC04263.webp"),
    soloSurfImg: image("imagenes-kitesurfing/posicionkt8.jpg"),
    rideCoastImg: image("fotos trip/DSC04697.webp"),
  }),
  "sections/ClassesPage/ClassesIntro.jsx": Object.freeze({
    introHover: image("fotos clases/DSC09570.webp"),
  }),
  "sections/ClassesPage/WingfoilClasses.jsx": Object.freeze({
    wingIntro: image("imagenes-wingfoil/posicionw1.jpg"),
    wingFundamental: image("imagenes-wingfoil/posicionw2.jpg"),
    wingAdvanced: image("imagenes-wingfoil/posicionw4.jpg"),
    wingMaster: image("imagenes-wingfoil/posicionw5.jpg"),
  }),
  "sections/ClassesPage/WingfoilIntro.jsx": Object.freeze({
    heroWingfoil: image("fotos wingfoil/DSC05634.webp"),
  }),
  "sections/ClassesPage/WingfoilWithUs.jsx": Object.freeze({
    gallery1: image("fotos wingfoil/DSC09936.webp"),
    gallery2: image("fotos wingfoil/DSC07146.webp"),
    gallery3: image("fotos wingfoil/DSC05634.webp"),
    gallery4: image("fotos wingfoil/DSC05417.webp"),
  }),
  "sections/ClassesPage/classesData.js": Object.freeze({
    heroKite: image("imagenes-kitesurfing/posicionkt1.jpg"),
    introKite: image("imagenes-kitsurfing-lessons/posicionk4.jpg"),
    introClassImg: image("imagenes-kitsurfing-lessons/posicionk1.jpg"),
    fundamentalClassImg: image("imagenes-kitsurfing-lessons/posicionk2.jpg"),
    introClassImgHover: image("fotos clases/DSC04663.webp"),
    advanceClassImg: image("fotos paquetes surf y hotel/IMG_6558.webp"),
    masterClassImg: image("fotos clases/DSC09584.webp"),
    gallery1: image("imagenes-wingfoil/posicionw1.jpg"),
    gallery2: image("imagenes-wingfoil/posicionw2.jpg"),
    gallery3: image("imagenes-wingfoil/posicionw4.jpg"),
    gallery4: image("imagenes-wingfoil/posicionw5.jpg"),
    gallery5: image("fotos wingfoil/DSC05369.webp"),
    gallery6: image("fotos wingfoil/DSC05362.webp"),
    gallery7: image("fotos clases/DSC04595.webp"),
    gallery8: image("fotos clases/DSC04273.webp"),
    gallery9: image("imagenes-home/posicion22.png"),
    gallery10: image("imagenes-home/posicion14y27.jpg"),
    gallery11: image("fotos clases/DSC07692.webp"),
    gallery12: image("fotos clases/DSC01412.webp"),
  }),
  "sections/ClassesPage/equipment/classesContent.js": Object.freeze({
    kiteImage: image("fotos clases/6dcb0367aacb508f64060f4c9f1b55f6.webp"),
    kiteImage2: image("fotos paquetes surf y hotel/DSC01088.webp"),
    kiteImage3: image("fotos clases/DSC07692.webp"),
    kiteImage4: image("imagenes-kitsurfing-lessons/posicionk1.jpg"),
    wingImg: image("imagenes-home/posicion14y27.jpg"),
    wingImg2: image("fotos wingfoil/DSC03425.webp"),
    wingImg3: image("fotos wingfoil/DSC03295.webp"),
    wingImg4: image("fotos wingfoil/DSC05417.webp"),
    wingImg5: image("fotos wingfoil/DSC05369.webp"),
  }),
  "sections/blogPage10/HeroSafariKite.jsx": Object.freeze({
    heroImg: image("fotos trip/DSC04699.webp"),
  }),
  "sections/blogPage11/HeroWhaleKite.jsx": Object.freeze({
    whaleHeroImg: image("fotos trip/DSC04250.webp"),
  }),
  "sections/blogPage12/HeroWhaleSeason.jsx": Object.freeze({
    heroImg: image("imagenes-home/posicion21.jpg"),
  }),
  "sections/blogPage13/HeroProgressionKite.jsx": Object.freeze({
    heroImg: image("fotos clases/DSC05719.webp"),
  }),
  "sections/blogPage14/HeroChoiceKite.jsx": Object.freeze({
    heroImg: image("fotos wingfoil/DSC00021.webp"),
  }),
  "sections/blogPage15/HeroSafetyProgression.jsx": Object.freeze({
    heroImg: image("imagenes-kitsurfing-lessons/posicionk6.jpg"),
  }),
  "sections/blogPage1/BlogHeroPage1/BlogHeroPage1.jsx": Object.freeze({
    heroImage: image("fotos clases/DSC07683.webp"),
  }),
  "sections/blogPage1/BlogLayoutPage1/BlogLayoutPage1.jsx": Object.freeze({
    mancoraImg: image("fotos trip/DSC05804.webp"),
    hawaiiImg: image("fotos clases/DSC09599.webp"),
    tarifaImg: image("imagenes-kitesurfing/posicionkt5.png"),
    capeTownImg: image("fotos trip/DSC03805.webp"),
    dakhlaImg: image("fotos trip/DSC07363.webp"),
    sectionBg: image("fotos trip/DSC03821.webp"),
  }),
  "sections/blogPage1/BlogTop/TopDestinationsSection.jsx": Object.freeze({
    sectionBg: image("imagenes-kitesurfing/posicionkt2.jpg"),
  }),
  "sections/blogPage1/blogContentPage1.js": Object.freeze({
    mancoraImg: image("fotos trip/DSC00587.webp"),
    hawaiiImg: image("imagenes-kitesurfing/posicionkt7.jpg"),
  }),
  "sections/blogPage1/destinationsData.js": Object.freeze({
    mancoraImg: image("fotos trip/DSC05804.webp"),
    hawaiiImg: image("fotos clases/DSC09627.webp"),
  }),
  "sections/blogPage2/BlogHeroPage2/HeroSevenPlans.jsx": Object.freeze({
    heroImg: image("fotos trip/DSC03906.webp"),
  }),
  "sections/blogPage2/BlogLayoutPage2/FinalCallToAction.jsx": Object.freeze({
    ctaBg: image("fotos trip/DSC03821.webp"),
  }),
  "sections/blogPage2/plansData.js": Object.freeze({
    planAImg: image("fotos trip/DSC03453.webp"),
    planBImg: image("fotos clases/DSC07683.webp"),
    planCImg: image("fotos trip/DSC03368.webp"),
    planDImg: image("fotos comunidad/DSC07841.webp"),
    planEImg: image("fotos trip/DSC03805.webp"),
    planFImg: image("fotos trip/DSC02043.webp"),
    planGImg: image("fotos clases/6e7948ecd00eab6741c0568662f61a53.webp"),
  }),
  "sections/blogPage3/BlogHeroPage3/blogHeroPage3.jsx": Object.freeze({
    heroImg: image("fotos clases/DSC04677.webp"),
  }),
  "sections/blogPage3/BlogLayoutPage3/ChicamaFinalCallToAction.jsx": Object.freeze({
    ctaImage: image("fotos clases/DSC04682.webp"),
  }),
  "sections/blogPage3/BlogLayoutPage3/ChicamaScroller.jsx": Object.freeze({
    imageOne: image("fotos clases/DSC06284.webp"),
    supportOne: image("fotos clases/DSC04664.webp"),
    imageTwo: image("fotos clases/DSC04670.webp"),
    supportTwo: image("fotos clases/DSC04672.webp"),
    imageThree: image("fotos mancora y mas/DSC09910.webp"),
    supportThree: image("fotos mancora y mas/DSC09912.webp"),
  }),
  "sections/blogPage3/BlogLayoutPage3/IntroChicama.jsx": Object.freeze({
    imageOne: image("fotos clases/DSC05740.webp"),
    imageTwo: image("fotos clases/DSC05905.webp"),
  }),
  "sections/blogPage3/galleyData.js": Object.freeze({
    img1: image("fotos clases/DSC02370.webp"),
    img2: image("fotos clases/DSC06284.webp"),
    img3: image("fotos clases/DSC06276.webp"),
    img4: image("fotos mancora y mas/DSC09933.webp"),
    img5: image("fotos mancora y mas/DSC09910.webp"),
  }),
  "sections/blogPage4/BlogHeroPage4/HeroMancoraVsLobitos.jsx": Object.freeze({
    heroImage: image("fotos trip/DSC07322.webp"),
  }),
  "sections/blogPage4/BlogLayoutPage4/IntroMancoraVsLobitos.jsx": Object.freeze({
    imageOne: image("fotos mancora y mas/DSC05505.webp"),
    imageTwo: image("fotos clases/DSC07694.webp"),
  }),
  "sections/blogPage4/BlogLayoutPage4/MancoraVsLobitosFinalCallToAction.jsx": Object.freeze({
    ctaImage: image("fotos home/DSC00231.webp"),
  }),
  "sections/blogPage4/BlogLayoutPage4/MancoraVsLobitosScroller.jsx": Object.freeze({
    imageOne: image("imagenes-home/posicion17.jpg"),
    supportOne: image("fotos trip/DSC03756.webp"),
    imageTwo: image("fotos mancora y mas/DSC05505 2.webp"),
    supportTwo: image("fotos comunidad/DSC07739.webp"),
    imageThree: image("imagenes-home/posicion29.jpg"),
    supportThree: image("fotos mancora y mas/DSC08663.webp"),
  }),
  "sections/blogPage4/comparisonData.js": Object.freeze({
    mancoraImg: image("fotos home/IMG_5230.webp"),
    lobitosImg: image("imagenes-home/posicion18.jpg"),
    caboImg: image("imagenes-kitesurfing/posicionkt4.jpg"),
  }),
  "sections/blogPage5/BlogHeroPage5/HeroPeruKitesurf.jsx": Object.freeze({
    heroImage: image("fotos home/DSC00231.webp"),
  }),
  "sections/blogPage5/BlogLayoutPage5/IntroPeruKitesurf.jsx": Object.freeze({
    imageOne: image("fotos clases/DSC07693.webp"),
    imageTwo: image("fotos comunidad/DSC08846.webp"),
  }),
  "sections/blogPage5/BlogLayoutPage5/PeruKitesurfFinalCallToAction.jsx": Object.freeze({
    ctaImage: image("fotos trip/DSC03821.webp"),
  }),
  "sections/blogPage5/BlogLayoutPage5/PeruKitesurfScroller.jsx": Object.freeze({
    imageOne: image("imagenes-home/posicion17.jpg"),
    supportOne: image("imagenes-kitesurfing/posicionkt7.jpg"),
    imageTwo: image("fotos trip/DSC03453.webp"),
    supportTwo: image("imagenes-home/posicion17.jpg"),
    imageThree: image("fotos trip/DSC03368.webp"),
    supportThree: image("fotos trip/DSC02043.webp"),
  }),
  "sections/blogPage6/BlogHeroPage6/HeroPacasmayo.jsx": Object.freeze({
    heroImage: image("fotos clases/DSC02370.webp"),
  }),
  "sections/blogPage6/BlogLayoutPage6/IntroPacasmayo.jsx": Object.freeze({
    imageOne: image("fotos clases/DSC04664.webp"),
    imageTwo: image("fotos clases/DSC04670.webp"),
  }),
  "sections/blogPage6/BlogLayoutPage6/PacasmayoFinalCallToAction.jsx": Object.freeze({
    ctaImage: image("fotos clases/DSC04677.webp"),
  }),
  "sections/blogPage6/BlogLayoutPage6/PacasmayoScroller.jsx": Object.freeze({
    imageOne: image("fotos mancora y mas/DSC05860.webp"),
    supportOne: image("fotos clases/DSC02370.webp"),
    imageTwo: image("fotos mancora y mas/DSC07164.webp"),
    supportTwo: image("fotos mancora y mas/DSC05276.webp"),
    imageThree: image("fotos mancora y mas/DSC03697.webp"),
    supportThree: image("fotos mancora y mas/DSC03698.webp"),
  }),
  "sections/blogPage7/BlogHeroPage7/WaveHero.jsx": Object.freeze({
    heroImg: image("fotos trip/DSC02043.webp"),
  }),
  "sections/blogPage8/HeroTechniquesKite.jsx": Object.freeze({
    heroImg: image("fotos clases/A66CFBBB-9C61-4CA4-9125-1360D41E5309.webp"),
  }),
  "sections/blogPage9/HeroMistakesKite.jsx": Object.freeze({
    heroImg: image("fotos clases/DSC06979 2.webp"),
  }),
  "sections/blog/BlogLayout/blogContent.js": Object.freeze({
    blogheroImage: image("fotos mancora y mas/IMG_3603.webp"),
    posicionK1: image("fotos clases/DSC06979 2.webp"),
    posicionK2: image("imagenes-kitesurfing/posicionkt3.jpg"),
    posicionK3: image("fotos home/DSC00406.webp"),
    posicionK4: image("imagenes-home/posicion18.jpg"),
    posicionK6: image("fotos clases/DSC07665.webp"),
    trending1: image("fotos clases/DSC06975 2.webp"),
    trending2: image("fotos clases/DSC06975 2.webp"),
    posicionW1: image("fotos clases/DSC05719.webp"),
    posicionW2: image("fotos wingfoil/DSC09982.webp"),
    posicionW5: image("fotos trip/DSC07365.webp"),
    posicionW6: image("imagenes-home/posicion21.jpg"),
    posicionW7: image("fotos home/DSC04249 2.webp"),
    surfPost1: image("fotos clases/DSC04679.webp"),
    surfPost2: image("fotos clases/DSC04682.webp"),
  }),
  "sections/common/Footer.jsx": Object.freeze({
    footerBrandLogo: image("LOGOS KITE CLUB/kite-LOGO-COMPLETE.webp"),
    logoDuotone: image("LOGOS KITE CLUB/Logo-duotone.webp"),
    logoOzone: image("LOGOS KITE CLUB/Logo_ozone.webp"),
    logoRide: image("LOGOS KITE CLUB/Logo-Ride.webp"),
    logoSlingshot: image("LOGOS KITE CLUB/Logo-slingshot.webp"),
  }),
  "sections/common/Header.jsx": Object.freeze({
    clubLogo: image("LOGOS KITE CLUB/kite-LOGO-COMPLETE.webp"),
  }),
  "sections/home/Movements.jsx": Object.freeze({
    logoOzone: image("LOGOS KITE CLUB/Logo_ozone.webp"),
    logoDuotone: image("LOGOS KITE CLUB/Logo-duotone.webp"),
    logoSlingshot: image("LOGOS KITE CLUB/Logo-slingshot.webp"),
    logoRide: image("LOGOS KITE CLUB/Logo-Ride.webp"),
  }),
  "sections/home/OurStory.jsx": Object.freeze({
    founderImg: image("fotos equipo/DSC07657.webp"),
  }),
  "sections/home/homeContent.js": Object.freeze({
    actionHeroDesktop: image("fotos home/DSC01032.webp"),
    actionHeroMobile: image("fotos home/DSC07629.webp"),
    waveHeroDesktop: image("fotos home/DSC08775.webp"),
    waveHeroMobile: image("fotos home/DSC07230.webp"),
    lifestyleHero: image("fotos home/DSC09510.webp"),
    beachHero: image("fotos home/DSC05908.webp"),
  }),
  "sections/home/Team.jsx": Object.freeze({
    founderImg: image("fotos comunidad/DSC02939.webp"),
    coach1: image("fotos comunidad/DSC04277.webp"),
    coach2: image("fotos comunidad/DSC06099.webp"),
    coach3: image("fotos comunidad/DSC09008.webp"),
  }),
  "sections/review/HeroReview.jsx": Object.freeze({
    reviewHeroImg: image("fotos comunidad/IMG_2917.webp"),
  }),
  "sections/waves/wavesContent.js": Object.freeze({
    heroImg: image("fotos trip/DSC04697.webp"),
    surfHeroImg: image("fotos mancora y mas/DSC01601.webp"),
    kiteSafariImg: image("fotos trip/DSC06167.webp"),
    kiteTripImg: image("fotos trip/DSC07145.webp"),
    kiteExperienceImg: image("fotos trip/DSC04260.webp"),
    wingDayImg: image("fotos wingfoil/DSC09982.webp"),
    wingProgressionImg: image("fotos wingfoil/DSC07130.webp"),
    wingExperienceImg: image("imagenes-wingfoil/posicionw8.jpg"),
    classBeginnerImg: image("fotos clases/DSC00433.webp"),
    classAdvancedImg: image("fotos clases/DSC09589.webp"),
    surfIntroImg: image("fotos mancora y mas/IMG_7170.webp"),
    surfAdventureImg: image("fotos clases/DSC00018.webp"),
    surfImmersionImg: image("imagenes-kitesurfing/posicionkt8.jpg"),
    surfClassBeginnerImg: image("fotos mancora y mas/DSC01601.webp"),
    surfClassAdvancedImg: image("fotos clases/DSC02370.webp"),
    mancoraImg: image("fotos mancora y mas/DSC02141.webp"),
    negritosImg: image("imagenes-wingfoil/posicionw7.jpg"),
    losOrganosImg: image("fotos comunidad/beach.webp"),
    caboBlancoImg: image("fotos mancora y mas/DSC05866.webp"),
    lobitosImg: image("fotos mancora y mas/DSC02131.webp"),
  }),
})

export const images = Object.freeze({
  brand: brandImages,
  media: mediaAssets,
  home: homeImages,
  hero: heroImages,
  trips: tripsImages,
  sponsors: sponsorImageSets,
  remote: remoteImages,
  seo: seoImages,
  component: componentImages,
})

export default images
